config/routes.rb
Muchtodo::Application.routes.draw do

  get 'todos/done' => 'todos#done', :as => :done

  root to: 'todos#index'

  resources :todos, except: :show

end

app/models/todo.rb
class Todo < ActiveRecord::Base

	attr_accessible :task, :priority, :status, :date_done

	PRIORITIES = ["high", "medium", "low"]
	STATUSES = ["to do", "done"]

	def self.tasks_to_do
		self.where(:status => STATUSES.index('to do')).order(:priority)
	end

	def self.tasks_done
		self.where(:status => STATUSES.index('done')).order(date_done: :desc).limit(5)
	end

	def update_attributes(params)
    if ((params[:status] == 'done') && (!self.done?))
      params[:date_done] = DateTime.now
    end
		super
	end

	def self.priorities
		PRIORITIES
	end

	def self.statuses
		STATUSES
	end

	# http://api.rubyonrails.org/classes/ActiveRecord/Base.html#class-ActiveRecord%3a%3aBase-label-Overwriting+default+accessors

	def priority=(str_value)
		p = write_attribute(:priority, PRIORITIES.index(str_value))
		raise "Error: Invalid priority" if p.nil?
	end

	def status=(str_value)
		s = write_attribute(:status, STATUSES.index(str_value))
		raise "Error: Invalid status" if s.nil?
	end

	def priority
		PRIORITIES[read_attribute(:priority)]
	end

	def status
		STATUSES[read_attribute(:status)]
	end

	def done?
		self.status == 'done' && !self.date_done.nil?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.tasks_to_do
  end

  def done
    @todos = Todo.tasks_done
  end

  def new
    @todo = Todo.new(:priority => 'high', :status => 'to do')
    @priorities = Todo.priorities
    @statuses = Todo.statuses
  end

  def create
    # investigate strong params -- not working, or don't understand somehow
    @todo = Todo.create!(params[:todo])
    redirect_to todos_path
  end

  def edit
    @todo = Todo.find_by_id(params[:id])
    @priorities = Todo.priorities
    @statuses = Todo.statuses
  end

  def update
    @todo = Todo.find params[:id]
    @todo.update_attributes(params[:todo])
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find params[:id]
    @todo.destroy
    redirect_to todos_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Muchtodo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<br />
<br />
This is my first Rails app. Check out the <a href="https://github.com/jimmylorunning/muchtodo">source</a> and give me some feedback!
</body>
</html>

app/views/todos/done.html.erb
<h1>Good Job Doing These!</h1>
<ul class="list-group">
<% @todos.each do |todo|  %>
	<li class="list-group-item <%= todo.priority %>"><%= todo.task %></li>
<% end %>
</ul>
<div align="center">
<%= link_to "Back to To Do list", todos_path, class: 'btn btn-default' %>
</div>
<%= debug(params) if Rails.env.development? %>

app/views/todos/edit.html.erb
<h1>Edit a Task</h1>
<%= form_for @todo, :html => {class: 'form-horizontal'} do |f| %>

	<div class="form-group">
	<%= f.label :task, class: 'col-sm-2 control-label' %>
	<div class="col-sm-9">
		<%= f.text_field :task, class: 'form-control'%>
	</div>
	</div>

	<div class="form-group">
	<%= f.label :priority, class: 'col-sm-2 control-label' %>
	<div class="col-sm-10">
		<%= f.select :priority, @priorities, class: 'form-control' %>
	</div>
	</div>

	<div class="form-group">
	<%= f.label :status, class: 'col-sm-2 control-label' %>
	<div class="col-sm-10">
		<%= f.select :status, @statuses, class: 'form-control'	 %>
	</div>
	</div>

	<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "Update", class: 'btn btn-default' %> &nbsp;
		<%= link_to "Cancel", todos_path, class: 'btn btn-default' %>
	</div>
	</div>
<% end %>

app/views/todos/index.html.erb
<h1>My To Do List</h1>
<table class="table todo-list">
	<tr>
		<th>Task</th>
		<th>Priority</th>
		<th colspan="2">Options</th>
	</tr>
<% @todos.each do |todo|  %>
<tr id="<%= todo.task.gsub(/\s+/, '') %>" class="<%= todo.priority %>"><td>
		<%= link_to todo.task, edit_todo_path(:id => todo.id) %>
	</td>
	<td>
		<%= todo.priority %>
	</td>
	<td>
		<%= form_for :todo, :url => {:action => 'update', :id => todo.id}, method: :patch do |f| %>
			<%= f.hidden_field :status, value: 'done' %>
			<%= f.submit "Done!", class: 'btn btn-default btn-sm' %>
		<% end %>
	</td>
	<td>
		<%= button_to 'Delete!', todo_path(todo), :method => 'delete', data: {confirm: 'Are you sure?'}, class: 'btn btn-default btn-sm' %>
	</td>
</tr>
<% end %>
</table>
<div align="center">
<%= link_to "Add", new_todo_path, class: 'btn btn-default btn-lg' %>
<br />
<br />
<%= link_to "See recently done", done_path %>
</div>
<%= debug(params) if Rails.env.development? %>

app/views/todos/new.html.erb
<h1>Add a New Task</h1>
<%= form_for @todo, :html => {class: 'form-horizontal'} do |f| %>

	<div class="form-group">
	<%= f.label :task, class: 'col-sm-2 control-label' %>
	<div class="col-sm-9">
		<%= f.text_field :task, class: 'form-control'%>
	</div>
	</div>

	<div class="form-group">
	<%= f.label :priority, class: 'col-sm-2 control-label' %>
	<div class="col-sm-10">
		<%= f.select :priority, @priorities, class: 'form-control' %>
	</div>
	</div>

	<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.hidden_field :status, value: 'to do' %>
		<%= f.submit "Add", class: 'btn btn-default' %> &nbsp;
		<%= link_to "Cancel", todos_path, class: 'btn btn-default' %>
	</div>
	</div>
<% end %>

app/views/todos/show.html.erb
show.html.erb